name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golang:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.26.5+auto
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: ci/test.sh

      - name: Build
        run: ci/build.sh
        env:
          GOTOOLCHAIN: go1.26.5+auto
