name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version: ~1.23.8
          cache: true

      - name: Test
        run: ci/test.sh

      - name: Build
        run: ci/build.sh

      - name: Latest image
        continue-on-error: true
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ci/docker-push.sh latest
