name: test

on:
  pull_request:

jobs:
  golang:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.26.5+auto
    steps:
      - uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: ci/test.sh

      - name: Build
        run: ci/build.sh
